### ISSUE TITLE
Nighlty linkcheck failed unexpectedly on Web Archive URL

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-docs#126]
## Expected behavior

The nightly run of `make docs-linkcheck` succeeds unless a URL is broken. (The job was introduced in #119.)

## Actual behavior

It failed, see [**linkcheck #170**][error].

## Steps to reproduce the problem

- Re-building the nightly job may reproduce the error ([**linkcheck #170**][error])

## Additional information

The cause of [the error][error] is not obvious to me:

```
Warning, treated as error:
/root/project/docs/getting_the_most_out_of_securedrop.rst.rst:86:broken link: https://web.archive.org/web/20201114212453/https://specialprojectsdesk.com/tell-on-trump-1792401813 (404 Client Error: Not Found for url: https://web.archive.org/web/20201118014447/https://specialprojectsdesk.com/tell-on-trump-1792401813)
make: *** [Makefile:17: docs-linkcheck] Error 2
```

Note the dates: `20201114212453` in the URL [that's the URL in the docs][link], and `20201118014447` in the URL that reports the `404 Client Error`.

I can't reproduce the error from a browser, I get a consistent HTTP 200 for the former URL. (The latter does indeed respond with HTTP 404, but I don't know yet how 'linkcheck' got there, I see no redirects in my browser logs.)

  [error]: https://app.circleci.com/pipelines/github/freedomofpress/securedrop-docs/174/workflows/218c1ca4-63a8-459a-9cfa-a4f3f021b43c/jobs/170
  [link]: https://github.com/freedomofpress/securedrop-docs/pull/118/files#diff-36ecf56ad6fe94f1f43551c7090ba8d17dbaf0faa64c28d3f96b8525a388478bR94

**Comment by eloquence** [comment]
I'm not sure exactly how IA's redirect logic works, but it looks like the link we added redirects to a later capture:

```
$ curl -I https://web.archive.org/web/20201114212453/https://specialprojectsdesk.com/tell-on-trump-1792401813

HTTP/2 302 
...
x-archive-redirect-reason: found capture at 20201114214553
location: https://web.archive.org/web/20201114214553/https://specialprojectsdesk.com/tell-on-trump-1792401813
```

That second URL does not redirect when `curl`ed and contains the expected content. Since the 404 is a legitimate site capture as well, perhaps we're being sporadically redirected to the wrong capture. I'd suggest trying the redirect target URL above.

**Comment by gonzalo-bulnes** [comment]
Ooh, my bad! I missed a number in the timestamp. And missed it when testing earlier as well. I can reproduce the redirection in Firefox as well as cURL. You're absolutely right.

The URL should have been `.../20201114214553/...` ending in `553`. I'll open a PR to fix that.

----

Now, I'm speculating, but when not finding a snapshot for a given timestamp, IA likely tries to match snapshots near in time. And malformed timestamps might be enough of an edge-case to not necessarily lead to very well defined behavior.
