### ISSUE TITLE
Recommend alternatives to SG-3100 firewall

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-docs#143]
According to https://store.netgate.com/SG-3100.aspx, the Netgate SG-3100 is unavailable until March 2021. We should find alternate 3- or 4-NIC ( pfSense compatible?) firewall recommendations, and test them.

**Comment by rocodes** [comment]
(Following up on internal comms) we have identified a few suitable alternative candidates for testing. Currently recommending the SG-5100 for time-sensitive hardware procurement, with at least one other lower-cost option being investigated and hopefully supported.

**Comment by eloquence** [comment]
Just noting here that the SG-3100 has been available again for a while and is not expected to reach end-of-sale in the foreseeable future. That said, we've committed to evaluating 1-2 additional firewalls, so keeping on near-term backlog.

**Comment by eloquence** [comment]
We now have three firewall recs in the docs so this can safely be closed.
