### ISSUE TITLE
Revise tails3-4 migration docs

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#145]
User reports that securedrop-admin setup fails during the apt stage on Tails 3 now with GPG key errors on the Tor repos. This makes sense as their key was updated recently. It also invalidates the instructions that say to upgrade to the latest SD version first before updating from Tails 3 to 4. They should be revised.

**Comment by eloquence** [comment]
I've revised this in #165 and added a disclaimer to this guide, which the PR also puts on a firm path to removal.
