### ISSUE TITLE
Add screenshots for disabling secure boot on nuc8

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-docs#151]
## Describe the change

This is a reminder to take screenshots of the bios for disabling secure boot on nuc8.

**Comment by eloquence** [comment]
The need to disable SecureBoot on NUCs is currently entirely undocumented; @creviera has committed to adding screenshots and brief instructions. We also discussed that it would be worthwhile to track & discuss SecureBoot support for SecureDrop core (cf. related issue for SecureDrop Workstation: https://github.com/freedomofpress/securedrop-workstation/issues/602)
