### ISSUE TITLE
Improve Landing Page docs

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-docs#184]
## Describe the change
The landing page guidelines are not just guidelines--there are certain requirements we have for listing an instance in our directory. We should clarify this and provide an easy way for instances to tell if they are in compliance or not (e.g. share our pass/fail criteria).

Also, while we're in there, we could consider updating our criteria to include the `Feature-Policy` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy) aka `Permissions-Policy` header (set to `none`). This is not supported by all browsers, but controls what kind of access the browser has to microphone, geolocation, battery status, and other APIs. 

## How will this impact users?
Landing page "guidelines" will be clearer and easier to interpret/implement before submitting instance verification form

## User Research Evidence
n/a just lots of instance verification correspondence

**Comment by gonzalo-bulnes** [comment]
Hi @rocodes, if you have a list of the requirements that an instance's landing page must meet to be listed in the directory, I think that would be useful to get an idea of how much work this page needs. I'm thinking it may be "not too much", but I may well be very wrong :slightly_smiling_face: 

Related issues: https://github.com/freedomofpress/securedrop-docs/issues/37, https://github.com/freedomofpress/securedrop-docs/issues/55

**Comment by gonzalo-bulnes** [comment]
Also related: https://github.com/freedomofpress/securedrop-docs/issues/46

**Comment by gonzalo-bulnes** [comment]
Related: https://github.com/freedomofpress/securedrop-docs/issues/210 (A place should be found in the landing page docs for that new information when it's defined.)
