### ISSUE TITLE
The network setup instructions for staging on Qubes OS can be miselading

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-docs#211]
## Context

In order to setup the network of a fresh Ubuntu (Focal) installation, a **subnet**, **address** and **gateway** must be provided.

The values for those three fields are interdependent, and the assumptions built into the current instructions are sometimes not fulfilled.

Specifically:

- the IP of the `sd-staging-base-focal` VM is assigned when the VM is created. Because of the the docs recommend reading its value via `qvm-prefs sd-staging-base-focal ip`. (Which is not wrong a all in itself.)
- the IP of the gateway that is visible to `sd-staging-base-focal` can also vary. Because of the the docs recommend reading its value via `qvm-prefs sd-staging-base-focal visible_gateway`. (Which, again, is not wrong a all in itself.)
- the suggested value for the netmask is suffix is `/24`. **This carries assumptions on the two values above.**

As far as I can tell, my Qubes OS network settings are the default (I use R4.1), despite that, *the assumption that the gateway would belong to the same `/24` network as the machine was not upheld in my case.*

- Address: `10.137.0.34` (`sd-staging-base-focal`)
- Gateway: `10.138.13.65` *which doesn't belong to the `10.137.0.0/24` subnet*
- Subnet: `10.136.0.0/14` is the smallest subnet that contains both `sd-staging-base-focal` and its gateway. ~(It can be written as `10.137.0.0/14` if that makes things easier to explain.)~

## Describe the change

I'm not sure what's the best balance between giving straightforward instructions and giving optimal instructions. Calculating the _subnet_ based on the _address_ and _gateway_ would give a correct and optimal solution, but adds steps to the setup.

I am currently [asking about reference Qubes OS documentation][ask] ([obsolete link][ask-old]) on the IP ranges that are used by default.
If suggesting a predefined suffix in the SecureDrop docs, I think it would be good to choose one that is broad enough to prevent as much network troubleshooting as possible given a fresh Qubes OS installation.

**Edit**: I think that recommending `10.136.0.0/14` would be reasonable given how Qubes OS allocates IP addresses to VMs (see comment below).

  [ask-old]: https://qubes-os.discourse.group/t/3870
  [ask]: https://forum.qubes-os.org/t/default-ip-ranges-for-sys-firewall-appvms-etc/3870

## How will this impact users?

After following the current instructions, my `sd-staging-base-focal` machine couldn't reach the internet to fetch updates. The intent behind providing specific instructions in the docs is to avoid troubleshooting when setting up servers.

## User Research Evidence

Anecdotical evidence based on my own experience setting up staging servers in Qubes OS.

## Additional context

Related to #209

**Comment by gonzalo-bulnes** [comment]
**Update**: the `10.138.xxx.xxx` (`10.138.0.0/16`) range is allocated by Qubes OS for DispVMs,. All other VMs get an IPv4 in the `10.137.xxx.xxx` (`10.137.0.0/16`).

The subnet `10.136.0.0/14` spans from `10.136.0.0` to `10.139.255.255`. Because it contains the entirety of both ranges above, I think it would be reasonable to recommend it in the docs that are specific to Qubes OS.

**Comment by gonzalo-bulnes** [comment]
cc: @creviera because we talked about that subnet setting :slightly_smiling_face:

**Comment by conorsch** [comment]
Hey, thanks for sharing the detailed research notes here! I largely duplicated this effort over in https://github.com/freedomofpress/securedrop-docs/pull/229#issuecomment-965827404, which was sloppy of me. Still, though, I believe that `10.137.0.0/24` is the sanest recommendation for this use case. Curious whether you agree with that analysis.

**Comment by gonzalo-bulnes** [comment]
Yep, I'm wrapping my head around your comment! But I cast the narrower subnet for **all** VMs, which may indeed be more than we need :+1:

**Comment by gonzalo-bulnes** [comment]
**Note**: I updated the link to the Qubes OS forum post. With the domain change the old one got obsolete.
