### ISSUE TITLE
Drop navigation bar "Checklists" section

### ISSUE THREAD

**Issue by damko** [freedomofpress/securedrop-docs#220]
## Describe the change
The "Pre-Install Hardware Checklist" is also included in "Hardware" page. I propose remove the "Checklists" section from the navigation bar.

## How will this impact users?
Unless there is a plan to expand the "Checklists" section with more lists, I believe that the "Checklists" section is redundant and, eventually, confusing. As a user, I like to be sure that all the hardware information is in the "Hardware" page (the reader doesn't know that the same text is included in two different pages so he might think that there could be differences in the content).

## User Research Evidence
No research evidence, just personal feeling.

**Comment by eloquence** [comment]
@damko I agree, it makes sense to remove this redundant section. Do you want to take a stab at PR to do so?

**Comment by damko** [comment]
Absolutely, will do. A couple of quests:
1. on which branch shall I start working from? main?
2. speaking of the hardware page, the included text sits in two fragment files (if I remember right). When I remove the checklist shall I remove the fragments and embed the content in the hardware page or shall I leave the fragments as they are (they aren't used in any other page than "hardware"). What's the best approach?

**Comment by eloquence** [comment]
> on which branch shall I start working from? main?

Yep!

> speaking of the hardware page, the included text sits in two fragment files (if I remember right). When I remove the checklist shall I remove the fragments and embed the content in the hardware page or shall I leave the fragments as they are (they aren't used in any other page than "hardware"). What's the best approach?

I suggest incorporating it into the main text, with a named reference tag before the section (see the "specific hardware recommendations" section for an example of the syntax), to make it easy to link to in future.

**Comment by nathandyer** [comment]
Fixed by PR #223
