### ISSUE TITLE
Rename navigation bar "Install Securedrop" section to "Deploy Securedrop"

### ISSUE THREAD

**Issue by damko** [freedomofpress/securedrop-docs#221]
## Describe the change
I propose to rename navigation bar "Install Securedrop" section to "Deploy Securedrop"

## How will this impact users?
More clarity. I'm not a native English speaker but "Install Securedrop" makes me think of installing a software. This whole section describes how to setup or deliver a whole system of hardware plus software therefore "Deploy Securedrop" seems more accurate.
Also, notice that in the same section there is a child page with title "Install Securedrop" which, at a first glance, seems like a repetition.

## User Research Evidence
No evidence, just personal taste.

**Comment by eloquence** [comment]
I agree that the "Installation" section currently has wider scope than a typical software installation - but note that we also already have a "Deployment Best Practices" section (mapped to a `deployment` folder in the docs), which covers stuff like the clearnet landing page, and the physical environment. I think if we reorganize here, we need to do more than just rename that one section.

**Comment by damko** [comment]
To be clear, my angle is to render the perception of a new comer. I believe that good documentation should be written by those who know and then evaluated by those who don't (my case).
@eloquence is there any plan in place for the reorganization of the doc?

**Comment by eloquence** [comment]
> @eloquence is there any plan in place for the reorganization of the doc?

Not really, but @gonzalo-bulnes has started some work in #141 to reorganize a section of the documentation following the Divio documentation system described here: https://documentation.divio.com/

I find the Divio system quite useful and would suggest we continue to keep it in mind for further changes to the information architecture.

**Comment by nathandyer** [comment]
The spirit of this issue was completed as part of the reorganization work in https://github.com/freedomofpress/securedrop-docs/pull/441
