### ISSUE TITLE
The instructions to set up Tails are out-of-date

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-docs#243]
## Expected behavior

The [documentation relative to setting up Tails](https://docs.securedrop.org/set_up_tails.html) is consistent with the [official Tails documentation](https://tails.boum.org/install/index.en.html).

## Actual behavior

I noticed two significant discrepancies today (current Tails version is 4.19), and I believe they may have been caused by improvements on Tails end:

1. The docs mention the Tails `.iso`, while Tails docs recommend installing from a `.img`. As a result, the download link seems obsolete and redundant, because the installation instruction on the Tails website go through the `.img` download and verification steps already.
2. The docs mention that:

   > It is only possible to set up persistence on USB drives which were created via the Tails Installer.

   The Tails installation instructions seem to indicate otherwise, but I'll create one and confirm. **Edit**: confirmed, the option of creating a persistent storage area is available after installing Tails like the official docs recommend.

## Additional information

~~Probably related to https://github.com/freedomofpress/securedrop-docs/issues/215 (because it is related to Tails 4.19).~~
Also worth having in mind: #63, #87, #90

I will be following those instructions soon(-ish), and I can PR updates as I do, if helpful.

**Comment by eloquence** [comment]
@gonzalo-bulnes You're quite right that these instructions are very dated! Tails switched to [USB disk images back in 2019](https://tails.boum.org/news/version_3.12/index.en.html), and our docs are still based on the previous installation method using the Installer. That process works, which is probably why nobody has noticed and fixed it, but it's unnecessarily complicated, and as you say, the wording is now inaccurate.

A PR would be very much appreciated! #215 is _not_ related -- that's a much more recent change in Tails 4.20, which I'll open a PR for now.

**Comment by gonzalo-bulnes** [comment]
I took a look today at what a PR would look like and noticed there is some interleaving between _explanations_ (that provide context) and step-by-step instructions (that are not always specific SecureDrop, e.g. Tails installation).

It seems to me that in Divio's terms, we're aiming at providing some **background information** on one hand, and something between a **tutorial** (the instructions are following steps that make sense to achieve the task efficiently, and the reader is not necessarily meant to have that insight - yet!) and a collection of **how-to guides** (some steps will be repeated multiple times, then every time a journalist comes on board, e.g. setting up a Tails USB). Am I reading this correctly?

I don't have an immediate idea of how the structure could make that more explicit, but I can think about it. I can also start by a very to-the-fact update of the Tails terminology, without minding the repetitions too much. What do you think is more useful or easier to review @eloquence?
