### ISSUE TITLE
Update docs screenshots for 2.1.0

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop-docs#262]
## Expected behavior
All screenshots on public docs are based on the most recent version of SD (2.1.0 at time of writing). 

## Actual behavior
Many screenshots are from 1.7.0. 

## Additional information
Looks like we never updated the screenshots for the 2.0.0 release. As part of https://github.com/freedomofpress/securedrop-docs/pull/260, I updated the screenshots for 2.1.0, but not all of them are included. For example, you can see both 2.1.0 and 1.7.0 screenshots here:

![sd-docs-210-incomplete](https://user-images.githubusercontent.com/657862/138006162-11ed03ff-1aac-4dc6-a8ed-043308a098d4.png)

Notice also that the last uploader used the "New York World" custom logo, whereas I still had the default SD logo configured. Let's make that consistent across the board.

**Comment by eloquence** [comment]
We've definitely often deferred the screenshot update if there were no major user-facing changes. Doing it with at least every minor-level release I think would be good practice to adhere to. 

I'd like to go back to the NYWorld logo (the idea is to strongly suggest that folks customize the logo), I can open a follow-up PR to #260 for that late today/tomorrow, doesn't have to go in today.

**Comment by conorsch** [comment]
Done. I'll push a `2.1.0-1` tag momentarily to update the stable docs.
