### ISSUE TITLE
Overview page improvements

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-docs#278]
## Describe the change

Add image and re-structure content, a bit. I'd love to see this make it into a near-term change, if @martinshelton or @huertanix feel this could be a good candidate for their near-term docs sprint. :) 

This ticket could also be split into two different PRs:
1st: An immediate update to just place the easier-to-parse image between the "Tip" and "Technical Summary"
2nd: Content re-structuring to speak first to users, second to the ecosystem, third to tech particulars, and fourth to organizational supportive requirements. "Technical Summary," "Infrastructure" (qualifying users as infra components), and "Operation" is very much framing our own universe through our eyes—and not so much through the lens of an editor, journalist, or business person with an NGO or news org.

## How will this impact users?
The SecureDrop website and docs both lack a general "Overview" to provide a non-technical anchoring for how SecureDrop works. It absolutely makes the effort—but could use some love to get past some base comprehension hurdle. Such a centering will be helpful to users, IT departments, customer prospects, and developers. 

## User Research Evidence

I will edit the Issues template, to omit this section.  

## Additional context

This image is not intended to show _everything_, only enough to inform mental models for the folks that don't know the difference between SSL and GPG. Existing image in "Infrastructure" will make much more sense, once a clearer image can be seeded in folks new to SD's noggins.

![HowSDWorks2](https://user-images.githubusercontent.com/8262612/142737736-1521a1d0-cf5d-4c73-9b19-ebd953891a00.png)

**Comment by ninavizz** [comment]
Adding link to Figma page for above diagram, in the SecureDrop Figma (under "Diagrams"): https://www.figma.com/file/Y7ZStJUr4maolaWIQhn0bq/How-SD-Works?node-id=0%3A1

**Comment by nathandyer** [comment]
These changes/improvements have happened naturally as the docs have expanded and been reorganized. Closing as completed.
