### ISSUE TITLE
Update Tails screenshots featuring the Applications > System Tools menu

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#291]
## Describe the change

The addition of the backup utility in 4.25 has changed the System Tools menu: it includes said utility now, and (annoyingly) it now has a scrollbar, with the user needing to scroll to bring the Terminal item into full view.

Since we refer to said item, and we wanna make sure users don't choose the Root Terminal item instead, it would be good to update screenshots illustrating it.

## How will this impact users?

Reduce opportunity for user error thru executing stuff as root

## User Research Evidence

nada

## Additional context

**Comment by eloquence** [comment]
Resolved via #372
