### ISSUE TITLE
Update documentation to reflect changes in Tails 5.0, when available

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#347]
## Describe the change

Tails 5.0 includes some UI changes as a result of the move to Debian 11. Docs and screenshots should be updated to match once Tails 5.0 is released (provisionally scheduled for mid-late May).

**Comment by DrWhax** [comment]
FWIW, i'm going through one right now:

- There's no settings button anymore under the top-right menu.
- Kleopatra is the new application to export PGP keys from.

**Comment by eloquence** [comment]
(Not fully resolved yet, some Journalist Guide updates pending.)
