### ISSUE TITLE
Provide a link in documentation to the Bridge information in the Tor support manual

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-docs#382]
Porting from: https://github.com/freedomofpress/securedrop/issues/2193#issuecomment-32479767:

> That being said, even if they download Tor discreetly, once they run Tor Browser it would be obvious they are connecting to the Tor network. Unless we want to advice people to use meek. meek is a Pluggable Transport that takes advantage of domain fronting to make it seem like you're connecting to either Amazon or Microsoft while you're actually connecting to Tor network.

**Comment by nathandyer** [comment]
After discussing this issue report during our summer cleanup session, we decided it was best not to recommend a specific bridge/method. That said, it would be worth adding a few sentences noting that if Tor does not connect, it may be blocked on the local network, in which case users should consult the [Tor Bridge documentation.](https://support.torproject.org/censorship/censorship-7/)

**Comment by nathandyer** [comment]
Upon further review, I'm not sure any changes are needed. It seems to me that the relevant place for this warning/link would be in the Journalist guide (the Source guide already advises potential sources to use a network that will allow them to connect directly to Tor, and the network configuration portion of the Admin guide takes care of those concerns there).

Currently, the documentation features the text:

"For more information about alternative ways to connect to the Tor network, please see the section [“Connecting to the Tor network”](https://tails.boum.org/doc/anonymous_internet/tor/index.en.html) in the Tails documentation."

Do we want to add some additional details, or is that sufficient (in which case, this can be closed)?

**Comment by zenmonkeykstop** [comment]
Yeah, IMO that's enough, feel free to just close this.

**Comment by nathandyer** [comment]
Closing this issue, as the documentation already covers this case.
