### ISSUE TITLE
rework developer documentation to prioritize common contributions (docs, webapp)

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-docs#40]
## Description

Our developer docs are in need of some attention mostly because we've made gradual changes over the past couple of years and as such the overall flow is confusing. Specifically, we should rewrite/reorganize them to more clearly distinguish the following scenarios:

1. Contributor wants to edit docs only.
2. Contributor wants to work on web app changes only (in which case they can just use the docker dev env and don't need to e.g. set up vagrant, rsync, etc. as described here: https://docs.securedrop.org/en/latest/development/setup_development.html#id2) - this is the most common development that happens in hackathons and drive-by contributions. 
3. Contributor wants to work on system configuration / provisioning - in this case they do need to be able to spin up staging. It is very rare for a hackathon participant to do contributions in this area due to the overhead involved. 

Since 1 and 2 are where most contributions happen, we should try to make those areas of the docs as clear as possible to someone unfamiliar with the project.

**Comment by eloquence** [comment]
@joaedwar Flagging for your visibility, relevant to your work on potentially revamping the entrypoint for new contributors.
