### ISSUE TITLE
Search is broken on docs.securedrop.org (and developers.securedrop.org)

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-docs#436]
## Expected behavior

Entering search term in search bar yields results page

## Actual behavior

Search hangs ("Searching [. .. ...]")

## Steps to reproduce the problem

1. (tested on firefox) visit docs.securedrop.org, enter any term in search bar and hit enter.

## Additional information
workstation.securedrop.org, also a RTD repo, is _not_ facing the same issue. developers.securedrop.org is facing this issue.

**Comment by legoktm** [comment]
```
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://docs.securedrop.org/en/stable/search.html?q=monitor&check_keywords=yes&area=default:193
[search.html:193:7](https://docs.securedrop.org/en/stable/search.html?q=monitor&check_keywords=yes&area=default)
    <anonymous> https://docs.securedrop.org/en/stable/search.html?q=monitor&check_keywords=yes&area=default:193
```

**Comment by legoktm** [comment]
Sphinx 6 removed jQuery - https://blog.readthedocs.com/sphinx6-upgrade/

In theory the sphinx_rtd_theme 1.2.0 should automatically pull in and enable jQuery, but it doesn't. Downgrading to sphinx 5.3.0 fixes the issue, I'll spend a bit debugging it before resorting to that to fix it.

**Comment by legoktm** [comment]
The installation instructions have changed (https://sphinx-rtd-theme.readthedocs.io/en/latest/installing.html), in addition to setting `html_theme`, we also need to add it as an extension. Doing that makes jQuery load and search works!

However, sphinxcontrib-jquery 2.0.0 loads jQuery from Google's CDN. We need to upgrade to 4.x to use a vendored copy.

PRs incoming
