### ISSUE TITLE
Merge existing content from redmine_docs into securedrop-docs

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#471]
- Merge existing git history from redmine_docs into securedrop-docs (conversation with @legoktm to come)
- update nav etc to reflect new content location

**Comment by legoktm** [comment]
What I had in mind to merge the git history in, is roughly (in a securedrop-docs checkout):
```
$ git remote add redmine git@github.com:freedomofpress/redmine_docs.git
$ git fetch redmine
$ git checkout -b support-docs redmine/main
```

Now you have a `support-docs` branch, with the full redmine_docs history, in the securedrop-docs repo. Then it's a matter of, in this branch, moving the files to new locations so they don't conflict (or deleting them), and then running `git merge main --allow-unrelated-histories`. (And if you hit file conflicts during merge, `git merge --abort`, adjust things, and then retry the merge again)
