### ISSUE TITLE
Set up URL redirects from old Redmine docs to new location

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#472]
- determine redirect regex/whatever based on new location
- Collaborate with infra team to add said redirects

**Comment by nathandyer** [comment]
A first attempt to compile a list of redirects can be found here: https://github.com/freedomofpress/securedrop-docs/pull/474#issuecomment-1640680519

**Comment by nathandyer** [comment]
Redirects were added following the merge of #474
