### ISSUE TITLE
Make Redmine docs merge live.

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#473]
Once content has been merged and redirects are ready to go, merge PR with content changes and tag a new stable release of securedrop-docs

**Comment by nathandyer** [comment]
Based on an earlier discussion in standup today, we realized that we are OK to go ahead and make the docs merge live prior to the redirects and the decommissioning of the old documentation site.

I've tagged a stable release, and everything is up and running. `redmine_docs` will be archived as soon as the redirects are fully in place.

Closing this as completed.
