### ISSUE TITLE
Research alternative firewall hardware

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#481]
Our hardware recco for OPNSense devices has been discontinued. We should revisit firewall recommendations in general to make sure that we have viable open-source options.

**Comment by zenmonkeykstop** [comment]
OPNSense is still an option and might be the preferred one for reccos if we can find a vendor that ships a reasonable device with it.

There are reasonable concerns about pfSense CE - that doesn't mean we rule out pfSense+ as an option instead, but the licensing change is definitely a point against.

**Comment by rocodes** [comment]
With the APUs being discontinued, I suggest we:
- Switch the recommendation to something generic ("An OPNSense firewall, ideally coreboot-compatible"), and optionally
- Suggest specific devices that conform to this standard ("An example of such is the 4-port Protectli Vault").
