### ISSUE TITLE
Add documentation on updating the SecureDrop release key expiration date

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-docs#52]
## Description

For bus factor reasons, we should document the process of bumping the expiration date for the SecureDrop release signing key (via the `securedrop-keyring` package). This guide should also include tasks like:

- [ ] Ensuring we've pushed the updated key to keyservers
- [ ] Ensuring we have updated the armored pub key that is on `securedrop.org`

**Comment by zenmonkeykstop** [comment]
Internal docs also outline the packaging and publishing steps. For now I think we can close this.
