### ISSUE TITLE
ark.intel.com NUC links are 404s

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-docs#539]
## Expected behavior

Links take you to the NUC product page

## Actual behavior

404 page not found error

## Steps to reproduce the problem

1. Visit https://docs.securedrop.org/en/stable/admin/installation/hardware.html#application-and-monitor-servers
1. Click on any/all of the ark.intel.com links

## Additional information

This was caught by the linkcheck CI job but we haven't been checking it recently it seems :/

**Comment by zenmonkeykstop** [comment]
All intel NUC support moved to Asus as of mid-January, so that's probably why
