### ISSUE TITLE
Documentation updates for SecureDrop 2.8.0

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-docs#544]
This is a tracking ticket to document changes pertaining to SecureDrop 2.8.0.

- [x] Tails 6 updates: https://github.com/freedomofpress/securedrop-docs/pull/538
- [x] Release boilerplate with reminder to migrate to Tails 6
- [x] Tails 6 migration instructions

**Comment by zenmonkeykstop** [comment]
This was completed
