### ISSUE TITLE
Migrate docs repositories to bookworm

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop-docs#567]
## Describe the change
Our docs repositories are currently built on Debian bullseye / Python 3.9, we should migrate them to bookworm as we're doing the same with the rest of our stack, and because we're starting to hit issues with 3.9 being less well supported upstream (e.g. https://github.com/sphinx-doc/sphinx-autobuild/issues/155).

* [x] securedrop-dev-docs: https://github.com/freedomofpress/securedrop-dev-docs/pull/164
* [x] securedrop-workstation-docs: https://github.com/freedomofpress/securedrop-workstation-docs/pull/220
* [x] securedrop-docs: https://github.com/freedomofpress/securedrop-docs/pull/574

**Comment by eloquence** [comment]
Unless you or someone else want to grab this, I can try to get this over the finish line this week, @legoktm.

**Comment by legoktm** [comment]
Go for it, I can do reviews then :)

**Comment by legoktm** [comment]
All done, thanks @eloquence!
