### ISSUE TITLE
Recommend a rack-mounted server in hardware notes

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop-docs#61]
# Feature request

## Description

The Freedom of the Press often gets asked by clients for specific hardware recommendation that they can put in a data center or on a rack. We should have a recommendation that is well tested for hardware compatibility. 

## User Stories

As a SecureDrop administrator, I would like to put a SD server in my data center.

**Comment by eloquence** [comment]
Still a valid issue; we are routinely testing with a couple of 1U models, and could potentially explicitly recommend one of them in the docs.

**Comment by zenmonkeykstop** [comment]
We have informal testing in place for Dell R440s and R620s but given the variety and cost of rackmounted hardware it would be hard to keep up to date with systems that are currently available. We're pursuing other avenues (better kernel testing, allowing for self-testing) to make a wider range of hardware available without formally recomending and testing against it.
