### ISSUE TITLE
Document appropriate fixes for errors in the Noble readiness script

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-docs#610]
https://github.com/freedomofpress/securedrop/pull/7334/ adds a check script to assess instances' readiness for an automatic update from Ubuntu 20.04 to 24.04. We should document the steps admins should take to resolve any issues that it finds.

**Comment by legoktm** [comment]
There are 5 checks currently:
* ssh: means upgrade in 2.11 failed / didn't work as expected - should send support the output of `getent group ssh`
* ufw: means upgrade in 2.11 failed / didn't work as expected - see output of securedrop-remove-packages service? run apt purge ufw yourself?
* free_space: they need to clean up their disk either by clearing stuff like `/var/cache` or deleting submissions??
   * maybe the check script can provide some hints here.
* apt: they have an unexpected apt source configured and tbh should reach out to support ASAP
* systemd: some unit is failing, need to use `systemctl list-units` to figure out which one and diagnose it
   * probably the script could also surface the failing units and say "run systemctl status <name> and journalctl -u <name>" for more info...
