### ISSUE TITLE
Need developer documentation for Ansible usage

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-docs#80]
## Description

A major portion of SecureDrop project is the huge amount of `Ansible` roles, playbooks. We need documentation for developers to understand the flow and the variables etc. Otherwise, every time a new developer (including me) tries to read the code base, the reaction is:

![confusing](https://user-images.githubusercontent.com/272303/62650069-a6a94700-b973-11e9-8fb6-da80ce2c7a41.gif)

**Comment by rmol** [comment]
Also: https://docs.ansible.com/ansible/latest/community/other_tools_and_programs.html#other-tools

**Comment by eloquence** [comment]
@kushaldas has started to write up some notes here: https://github.com/freedomofpress/securedrop/wiki/Usage-of-Molecule-and-Ansible-for-development

(We should decide if this belongs in the wiki or the main developer docs.)

**Comment by kushaldas** [comment]
We should be able to review https://github.com/freedomofpress/securedrop/wiki/Usage-of-Molecule-and-Ansible-for-development as it is a wiki page, we can modify it as part of the review process.

**Comment by emkll** [comment]
Thanks for creating and populating the wiki page @kushaldas . I have taken the liberty of adding a graph of the securedrop-prod playbook generated by ansible-playbook-grapher for background. Closing this issue for now, but we can either reopen this issue or open more specific issues in the future to improve developer docs.
