### ISSUE TITLE
Standardize naming of "Master" Tails USB aka "Primary" Tails USB 

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-docs#90]
The master/primary Tails USB device, originally used to create SVS, Admin WS and Journo WS via cloning, and subsequently used to perform offline updates of the SVS (and/or back up all the workstations) should probably be referred to by one name throughout our docs, and should maybe even be added to the glossary. 

Working on writing clear docs for the Tails Update process, especially for the SVS (see freedomofpress/securedrop#2244) and looking for a clear and concise way to reference this device, and also noticing that it is referred to as mostly the "master" Tails USB but sometimes the primary Tails USB. 

It's important to clarify that this "primary" device is just a utility and doesn't contain any important data (which isn't intuitive, given the name). If I didn't know better, I would maybe think that the Primary Tails USB was another name for the Admin workstation.  

In particular, this section of this docs is a bit confusing: https://docs.securedrop.org/en/stable/backup_workstations.html?backup-the-workstations
 
Any thoughts?

**Comment by zenmonkeykstop** [comment]
How about "reference Tails USB"? It's not the primary/master in any real sense, as you point out.

**Comment by gonzalo-bulnes** [comment]
Putting in my two cents: "Template Tails USB"?

**Comment by simonft** [comment]
In case it's useful feedback, I ran into this in the backup instructions and was confused for a bit trying to figure out what the _primary Tails USB_ was, and whether it was different from the master tails USB. I don't have any particularly useful thoughts on a better name though.
